// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1Qa62VGHN0aEF46rmkQWLLlz_PxoMFA',
    appId: '1:693132385676:web:4c28d9bc8af8b6e0890aa9',
    messagingSenderId: '693132385676',
    projectId: 'flutter-jobs4dent',
    authDomain: 'flutter-jobs4dent.firebaseapp.com',
    storageBucket: 'flutter-jobs4dent.firebasestorage.app',
    measurementId: 'G-MMDTGGDY33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUkkfFwTmmaiH6WALVE7nwTcGeWCZLFc',
    appId: '1:693132385676:android:68d5f7ecd83909ad890aa9',
    messagingSenderId: '693132385676',
    projectId: 'flutter-jobs4dent',
    storageBucket: 'flutter-jobs4dent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdEu1PvH_yroPHFXixS7mxG36BynbeIo',
    appId: '1:693132385676:ios:f02e307f92d035de890aa9',
    messagingSenderId: '693132385676',
    projectId: 'flutter-jobs4dent',
    storageBucket: 'flutter-jobs4dent.firebasestorage.app',
    iosBundleId: 'bavonparadon.prapon.jobs4dent',
  );
}
